name: pull request comment
on:
  issue_comment:                                     
      types: [created, edited, deleted]

jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:

      - name: Azure Login
        if: contains(github.event.comment.body, '/deploy')
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        if: contains(github.event.comment.body, '/deploy')
        uses: actions/checkout@v2

      - name: 'Build and push image'
        if: contains(github.event.comment.body, '/deploy')
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -f ./AcrHelloworld/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}

      - name: 'Comment' 
        if: contains(github.event.comment.body, '/deploy')
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ secrets.REGISTRY_LOGIN_SERVER }}/testapp:${{ github.sha }}
            })
#'👋 Thanks for reporting!'
      # - name: Build
      #   if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
      #   uses: docker/build-push-action@v2
      #   with:
      #       load: true
      #       context: .
      #       file: ./AcrHelloworld/Dockerfile
      #       tags: ghcr.io/lei9444/test

      # - name: Inspect
      #   if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
      #   run: |
      #     docker push ghcr.io/lei9444/test
      # - name: test
      #   if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
      #   run: |
      #     echo test
