name: pull request comment
on:
  issue_comment:                                     
      types: [created, edited, deleted]

jobs:
  job01:
    if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
    runs-on: [ubuntu-latest]
    steps:

      - name: Checkout
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITGUB_PAT }}
          registry: ghcr.io
          repository: test
          tags: ${{ github.sha }}
          dockerfile: Dockerfile

      # - name: Build
      #   if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
      #   uses: docker/build-push-action@v2
      #   with:
      #       push: false
      #       context: .
      #       file: ./AcrHelloworld/Dockerfile
      #       tags: test
      # - name: test
      #   if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
      #   run: |
      #     echo test
