name: Remove related container 

on:
  pull_request:
    types: [ closed ]

jobs:
  close_job:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Container
        id: run
        uses: fjogeleit/http-request-action@master
        with:
          url: 'http://40.112.182.205:5000/api/image/delete'
          method: 'POST'
          data: '{"version":${{github.event.pull_request.number}}}'
          timeout: 600000
